# Generated by Django 4.2.16 on 2024-10-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
